# -*- coding: utf-8 -*-
"""
Created on Tue Sep 21 21:34:28 2021

@author: adesuyi-m
"""

#AdvancedAnalytics Packages
from AdvancedAnalytics.Forest import forest_classifier
from AdvancedAnalytics.Tree import tree_classifier
from AdvancedAnalytics.Regression import logreg, stepwise
from AdvancedAnalytics.ReplaceImputeEncode import DT, ReplaceImputeEncode
from AdvancedAnalytics.NeuralNetwork import nn_classifier

#SKLearn Packages
from sklearn.metrics         import f1_score,precision_score,recall_score,confusion_matrix,plot_confusion_matrix
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import cross_validate
from sklearn.model_selection import train_test_split
from sklearn.metrics import plot_roc_curve
from sklearn.tree import DecisionTreeClassifier
from sklearn.neural_network import MLPClassifier

#Import Python Packages
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import statsmodels.api as sm

folder = 'C:\\Users\\adesuyi-m\\Documents\\Humana Competition\\'
training_clean_full = pd.read_pickle(folder+'training_clean_full.pkl')

zero_list = []
desc = training_clean_full.describe()
for c in desc.columns:
    if desc[c][1] == 0.0:
        if desc[c][2] == 0.0:
            zero_list.append(c)

training_clean_full.drop(zero_list,axis=1,inplace=True)

training_clean_full = training_clean_full.replace('*',None)
training_clean_full = training_clean_full.replace(np.nan,None)

string_list = [l for l in dict(training_clean_full.dtypes) if training_clean_full.dtypes[l] == 'object'][1:]
num_list = [l for l in dict(training_clean_full.dtypes) if training_clean_full.dtypes[l] in ['int64','float64']]

training_clean_full[string_list] = training_clean_full[string_list].astype(str)


data_map = {
	'ID': 		                              [ DT.Ignore   ,  ],
	'rx_gpi2_72_pmpm_cost_6to9m_b4': 	      [ DT.Interval , (-0.5, 3842.7168) ],
	'atlas_pct_laccess_child15': 	              [ DT.Interval , (-0.5, 31.656) ],
	'atlas_recfacpth14': 	                      [ DT.Interval , (-0.5, 1.1106) ],
	'atlas_pct_fmrkt_frveg16': 	              [ DT.Interval , (-0.5, 100.5) ],
	'atlas_pct_free_lunch14': 	              [ DT.Interval , (-0.4903, 100.5) ],
	'bh_ncal_pmpm_ct': 	                      [ DT.Interval , (-0.5, 5.8333) ],
	'src_div_id': 	                              [ DT.Nominal  , (0.0, 1.0, 2.0, 3.0, 4.0, 5.0) ],
	'total_bh_copay_pmpm_cost_t_9-6-3m_b4':       [ DT.Nominal  , ('Dec_1x-2x', 'Dec_2x-4x', 'Dec_4x-8x', 'Dec_over_8x', 'Inc_1x-2x', 'Inc_2x-4x', 'Inc_4x-8x', 'Inc_over_8x', 'New', 'No Activity', 'No_Change', 'Resolved') ],
	'cons_chmi': 	                              [ DT.Interval , (-0.5, 255.5) ],
	'mcc_ano_pmpm_ct_t_9-6-3m_b4': 	              [ DT.Nominal  , ('Dec_1x-2x', 'Dec_2x-4x', 'Inc_1x-2x', 'New', 'No Activity', 'No_Change', 'Resolved') ],
	'rx_maint_pmpm_cost_t_12-9-6m_b4': 	      [ DT.Nominal  , ('Dec_1x-2x', 'Dec_2x-4x', 'Dec_4x-8x', 'Dec_over_8x', 'Inc_1x-2x', 'Inc_2x-4x', 'Inc_4x-8x', 'Inc_over_8x', 'New', 'No Activity', 'No_Change', 'Resolved') ],
#	'cons_ltmedicr': 	                      [ DT.Ignore   , (-0.5, 9.5) ],
	'rx_gpi4_6110_pmpm_ct': 	              [ DT.Interval , (-0.5, 1.5833) ],
	'atlas_pc_snapben15': 	                      [ DT.Interval , (1.5808, 80.4416) ],
	'credit_bal_nonmtgcredit_60dpd': 	      [ DT.Interval , (78.38, 14805.3446) ],
	'rx_bh_mbr_resp_pmpm_cost_9to12m_b4':         [ DT.Interval , (-0.5, 542.75) ],
	'rx_nonbh_pmpm_cost_t_9-6-3m_b4': 	      [ DT.Nominal  , ('Dec_1x-2x', 'Dec_2x-4x', 'Dec_4x-8x', 'Dec_over_8x', 'Inc_1x-2x', 'Inc_2x-4x', 'Inc_4x-8x', 'Inc_over_8x', 'New', 'No Activity', 'No_Change', 'Resolved') ],
	'atlas_pct_laccess_nhna15': 	              [ DT.Interval , (-0.5, 58.3662) ],
	'credit_hh_nonmtgcredit_60dpd': 	      [ DT.Interval , (1.5351, 66.7352) ],
	'rx_bh_pmpm_ct_0to3m_b4': 	              [ DT.Interval , (-0.5, 7.5) ],
	'cons_lwcm10': 	                              [ DT.Interval , (-0.4741, 1.3209) ],
	'atlas_fsrpth14': 	                      [ DT.Interval , (-0.5, 4.8685) ],
	'auth_3mth_dc_home': 	                      [ DT.Interval , (0.0, 3.0) ],
	'atlas_wicspth12': 	                      [ DT.Interval , (-0.5, 2.2331) ],
	'rx_gpi2_17_pmpm_cost_t_12-9-6m_b4':          [ DT.Nominal  , ('Dec_1x-2x', 'Dec_2x-4x', 'Inc_1x-2x', 'Inc_2x-4x', 'Inc_4x-8x', 'New', 'No Activity', 'No_Change', 'Resolved') ],
	'cons_hxmioc': 	                              [ DT.Interval , (-0.5, 9.5) ],
	'rx_generic_pmpm_cost_t_6-3-0m_b4':           [ DT.Nominal  , ('Dec_1x-2x', 'Dec_2x-4x', 'Dec_4x-8x', 'Dec_over_8x', 'Inc_1x-2x', 'Inc_2x-4x', 'Inc_4x-8x', 'Inc_over_8x', 'New', 'No Activity', 'No_Change', 'Resolved') ],
	'cmsd2_sns_digest_abdomen_pmpm_ct':           [ DT.Interval , (-0.5, 10.125) ],
	'atlas_ghveg_farms12': 	                      [ DT.Interval , (-0.5, 150.5) ],
	'credit_hh_bankcardcredit_60dpd': 	      [ DT.Interval , (-0.46, 31.8409) ],
	'total_outpatient_allowed_pmpm_cost_6to9m_b4':[ DT.Interval , (-0.5, 26247.13) ],
	'cons_cwht': 	                              [ DT.Interval , (-0.5, 99.5) ],
	'atlas_netmigrationrate1016': 	              [ DT.Interval , (-16.2152, 43.478) ],
	'atlas_pct_laccess_snap15': 	              [ DT.Interval , (-0.5, 29.2418) ],
	'bh_ncdm_ind': 	                              [ DT.Binary   , (0, 1) ],
	'rx_nonmaint_mbr_resp_pmpm_cost_9to12m_b4':   [ DT.Interval , (-0.5, 1453.42) ],
	'atlas_retirement_destination_2015_upda':     [ DT.Binary   , (0.0, 1.0) ],
	'rx_overall_mbr_resp_pmpm_cost_t_6-3-0m_b4':  [ DT.Nominal  , ('Dec_1x-2x', 'Dec_2x-4x', 'Dec_4x-8x', 'Dec_over_8x', 'Inc_1x-2x', 'Inc_2x-4x', 'Inc_4x-8x', 'Inc_over_8x', 'New', 'No Activity', 'No_Change', 'Resolved') ],
	'atlas_naturalchangerate1016': 	              [ DT.Interval , (-7.0106, 14.8181) ],
	'ccsp_236_pct': 	                      [ DT.Interval , (-0.5, 11.9221) ],
	'rx_overall_dist_gpi6_pmpm_ct_t_6-3-0m_b4':   [ DT.Nominal  , ('Dec_1x-2x', 'Dec_2x-4x', 'Dec_4x-8x', 'Dec_over_8x', 'Inc_1x-2x', 'Inc_2x-4x', 'Inc_4x-8x', 'Inc_over_8x', 'New', 'No Activity', 'No_Change', 'Resolved') ],
	'atlas_pct_laccess_hisp15': 	              [ DT.Interval , (-0.5, 63.1906) ],
	'auth_3mth_dc_no_ref': 	                      [ DT.Interval , (0.0, 1.0) ],
	'rx_overall_mbr_resp_pmpm_cost': 	      [ DT.Interval , (-0.5, 1678.3184) ],
	'rx_overall_gpi_pmpm_ct_0to3m_b4': 	      [ DT.Interval , (-0.5, 42.1667) ],
	'auth_3mth_dc_snf': 	                      [ DT.Interval , (0.0, 2.0) ],
	'rx_phar_cat_humana_pmpm_ct_t_9-6-3m_b4':     [ DT.Nominal  , ('Dec_1x-2x', 'Dec_2x-4x', 'Dec_4x-8x', 'Dec_over_8x', 'Inc_1x-2x', 'Inc_2x-4x', 'Inc_4x-8x', 'Inc_over_8x', 'New', 'No Activity', 'No_Change', 'Resolved') ],
	'atlas_pct_laccess_hhnv15': 	              [ DT.Interval , (-0.5, 46.4558) ],
	'auth_3mth_acute_end': 	                      [ DT.Interval , (0, 1) ],
	'auth_3mth_psychic': 	                      [ DT.Interval , (0.0, 1.0) ],
	'atlas_hiamenity': 	                      [ DT.Binary   , (0.0, 1.0) ],
	'auth_3mth_bh_acute': 	                      [ DT.Interval , (0.0, 1.0) ],
	'credit_bal_consumerfinance': 	              [ DT.Interval , (89.3571, 5341.1712) ],
	'auth_3mth_acute_chf': 	                      [ DT.Interval , (0.0, 1.0) ],
	'rx_overall_gpi_pmpm_ct_t_6-3-0m_b4': 	      [ DT.Nominal  , ('Dec_1x-2x', 'Dec_2x-4x', 'Dec_4x-8x', 'Dec_over_8x', 'Inc_1x-2x', 'Inc_2x-4x', 'Inc_4x-8x', 'Inc_over_8x', 'New', 'No Activity', 'No_Change', 'Resolved') ],
	'rwjf_uninsured_pct': 	                      [ DT.Interval , (-0.4787, 0.8302) ],
	'mcc_chf_pmpm_ct_t_9-6-3m_b4': 	              [ DT.Nominal  , ('Dec_1x-2x', 'Dec_2x-4x', 'Dec_4x-8x', 'Dec_over_8x', 'Inc_1x-2x', 'Inc_2x-4x', 'Inc_4x-8x', 'Inc_over_8x', 'New', 'No Activity', 'No_Change', 'Resolved') ],
	'rx_mail_mbr_resp_pmpm_cost_0to3m_b4': 	      [ DT.Interval , (-0.5, 1218.79) ],
	'bh_urgent_care_copay_pmpm_cost_t_12-9-6m_b4':[ DT.Nominal  , ('No Activity', 'No_Change') ],
	'atlas_pct_wic15': 	                    [ DT.Interval , (0.6051, 3.7316) ],
	'ccsp_193_pct': 	                    [ DT.Interval , (-0.5, 8.5) ],
	'auth_3mth_dc_hospice': 	            [ DT.Interval , (0, 1) ],
	'atlas_pct_fmrkt_baked16': 	            [ DT.Interval , (-0.5, 100.5) ],
	'rx_nonmaint_mbr_resp_pmpm_cost': 	    [ DT.Interval , (-0.5, 1336.7341) ],
	'auth_3mth_acute_skn': 	                    [ DT.Interval , (0.0, 1.0) ],
	'atlas_veg_farms12': 	                    [ DT.Interval , (-0.5, 815.5) ],
	'atlas_vlfoodsec_13_15': 	            [ DT.Interval , (2.4, 8.4) ],
	'rx_gpi2_34_dist_gpi6_pmpm_ct': 	    [ DT.Interval , (-0.5, 1.5) ],
	'bh_ip_snf_net_paid_pmpm_cost': 	    [ DT.Interval , (-0.5, 1180.7633) ],
	'credit_hh_bankcard_severederog': 	    [ DT.Interval , (-0.4878, 27.3696) ],
	'rx_hum_16_pmpm_ct': 	                    [ DT.Interval , (-0.5, 12.0) ],
	'est_age': 	                            [ DT.Interval , (19.5, 104.5) ],
	'rx_maint_pmpm_cost_t_6-3-0m_b4': 	    [ DT.Nominal  , ('Dec_1x-2x', 'Dec_2x-4x', 'Dec_4x-8x', 'Dec_over_8x', 'Inc_1x-2x', 'Inc_2x-4x', 'Inc_4x-8x', 'Inc_over_8x', 'New', 'No Activity', 'No_Change', 'Resolved') ],
	'cnt_cp_webstatement_pmpm_ct':              [ DT.Interval , (-0.5, 41.0) ],
	'atlas_pct_laccess_seniors15': 	            [ DT.Interval , (-0.5, 28.4463) ],
	'phy_em_px_pct': 	                    [ DT.Interval , (-0.5, 12.5) ],
	'atlas_percapitainc': 	                    [ DT.Interval , (7123.5, 66522.5) ],
	'rwjf_uninsured_adults_pct': 	            [ DT.Interval , (-0.4738, 0.934) ],
	'rx_generic_mbr_resp_pmpm_cost_0to3m_b4':   [ DT.Interval , (-0.5, 671.2067) ],
	'rwjf_air_pollute_density': 	            [ DT.Interval , (4.0, 15.9) ],
	'rx_gpi2_02_pmpm_cost': 	            [ DT.Interval , (-0.5, 100.5) ],
	'atlas_recfac14': 	                    [ DT.Interval , (-0.5, 845.5) ],
	'cons_mobplus': 	                    [ DT.Nominal  , ('M', 'P', 'S', 'U') ],
	'lab_albumin_loinc_pmpm_ct': 	            [ DT.Interval , (-0.5, 1.5) ],
	'atlas_pct_obese_adults13': 	            [ DT.Interval , (11.3, 46.8) ],
	'rx_maint_net_paid_pmpm_cost_t_12-9-6m_b4': [ DT.Nominal  , ('Dec_1x-2x', 'Dec_2x-4x', 'Dec_4x-8x', 'Dec_over_8x', 'Inc_1x-2x', 'Inc_2x-4x', 'Inc_4x-8x', 'Inc_over_8x', 'New', 'No Activity', 'No_Change', 'Resolved') ],
	'rev_pm_obsrm_pmpm_ct': 	            [ DT.Interval , (-0.5, 3.0) ],
	'atlas_pct_sfsp15': 	                    [ DT.Interval , (-0.2729, 4.7713) ],
	'total_physician_office_net_paid_pmpm_cost_9to12m_b4': 	[ DT.Interval , (-0.5, 541.475) ],
	'atlas_pc_dirsales12': 	                                [ DT.Interval , (-0.5, 126.9246) ],
	'med_ip_snf_admit_days_pmpm': 	                        [ DT.Interval , (-0.5, 13.1667) ],
	'rej_med_outpatient_visit_ct_pmpm_t_6-3-0m_b4': 	[ DT.Nominal  , ('Dec_1x-2x', 'Dec_2x-4x', 'Dec_4x-8x', 'Inc_1x-2x', 'Inc_2x-4x', 'Inc_4x-8x', 'New', 'No Activity', 'No_Change', 'Resolved') ],
	'cms_tot_partd_payment_amt': 	                        [ DT.Interval , (-0.5, 813.56) ],
	'rx_nonotc_dist_gpi6_pmpm_ct': 	                        [ DT.Interval , (-0.5, 13.5) ],
	'rx_nonmaint_pmpm_ct': 	                                [ DT.Interval , (-0.5, 18.0) ],
	'rx_nonbh_mbr_resp_pmpm_cost_6to9m_b4': 	        [ DT.Interval , (-0.5, 2233.0632) ],
	'cons_stlnindx': 	                                [ DT.Interval , (-0.5, 9.5) ],
	'atlas_hipov_1115': 	                                [ DT.Binary   , (0.0, 1.0) ],
	'rx_nonbh_mbr_resp_pmpm_cost': 	                        [ DT.Interval , (-0.5, 1651.5841) ],
	'atlas_redemp_snaps16': 	                        [ DT.Interval , (0.4989, 827698.2406) ],
	'atlas_berry_farms12': 	                                [ DT.Interval , (-0.5, 360.5) ],
	'rej_med_ip_snf_coins_pmpm_cost_t_9-6-3m_b4': 	        [ DT.Nominal  , ('No Activity', 'No_Change') ],
	'rwjf_inactivity_pct': 	                                [ DT.Interval , (-0.402, 0.944) ],
	'rx_gpi2_72_pmpm_ct_6to9m_b4': 	                        [ DT.Interval , (-0.5, 4.5) ],
	'cons_n2pmr': 	                                        [ DT.Interval , (-0.5, 92.5) ],
	'med_physician_office_allowed_pmpm_cost_t_9-6-3m_b4': 	[ DT.Nominal  , ('Dec_1x-2x', 'Dec_2x-4x', 'Dec_4x-8x', 'Dec_over_8x', 'Inc_1x-2x', 'Inc_2x-4x', 'Inc_4x-8x', 'Inc_over_8x', 'New', 'No Activity', 'No_Change', 'Resolved') ],
	'auth_3mth_acute_res': 	                                [ DT.Interval , (0.0, 1.0) ],
	'rev_cms_ct_pmpm_ct': 	                                [ DT.Interval , (-0.5, 1.8333) ],
	'atlas_foodhub16': 	                                [ DT.Interval , (0.0, 6.0) ],
	'total_physician_office_copay_pmpm_cost': 	        [ DT.Interval , (-0.5, 118.7342) ],
	'auth_3mth_acute_dig': 	                                [ DT.Interval , (0.0, 1.0) ],
	'auth_3mth_dc_acute_rehab': 	                        [ DT.Interval , (0.0, 1.0) ],
	'atlas_pct_fmrkt_anmlprod16': 	                        [ DT.Interval , (-0.5, 100.5) ],
	'credit_num_agencyfirstmtg': 	                        [ DT.Interval , (-0.5, 1.2297) ],
	'total_physician_office_net_paid_pmpm_cost_t_9-6-3m_b4':[ DT.Nominal  , ('Dec_1x-2x', 'Dec_2x-4x', 'Dec_4x-8x', 'Dec_over_8x', 'Inc_1x-2x', 'Inc_2x-4x', 'Inc_4x-8x', 'Inc_over_8x', 'New', 'No Activity', 'No_Change', 'Resolved') ],
	'atlas_type_2015_mining_no': 	                        [ DT.Binary   , (0.0, 1.0) ],
	'atlas_agritrsm_rct12': 	                        [ DT.Interval , (-0.5, 6899000.5) ],
	'rx_days_since_last_script': 	                        [ DT.Interval , (0.5, 480.5) ],
	'atlas_pct_laccess_pop15': 	                        [ DT.Interval , (-0.5, 100.5) ],
	'auth_3mth_post_acute_res': 	                        [ DT.Interval , (0, 1) ],
	'auth_3mth_acute_inf': 	                                [ DT.Interval , (0, 1) ],
	'rx_gpi2_01_pmpm_cost_0to3m_b4': 	                [ DT.Interval , (-0.5, 352.55) ],
	'atlas_povertyallagespct': 	                        [ DT.Interval , (2.9, 45.7) ],
	'covid_vaccination': 	                                [ DT.Binary   , ('no_vacc', 'vacc') ],
	'rwjf_uninsured_child_pct': 	                        [ DT.Interval , (-0.4917, 0.743) ],
	'rx_branded_pmpm_ct_t_6-3-0m_b4': 	                [ DT.Nominal  , ('Dec_1x-2x', 'Dec_2x-4x', 'Dec_4x-8x', 'Dec_over_8x', 'Inc_1x-2x', 'Inc_2x-4x', 'Inc_4x-8x', 'Inc_over_8x', 'New', 'No Activity', 'No_Change', 'Resolved') ],
	'med_outpatient_deduct_pmpm_cost_t_9-6-3m_b4': 	        [ DT.Nominal  , ('Dec_1x-2x', 'Dec_2x-4x', 'Dec_4x-8x', 'Dec_over_8x', 'Inc_1x-2x', 'Inc_2x-4x', 'New', 'No Activity', 'No_Change', 'Resolved') ],
	'credit_bal_mtgcredit_new': 	                        [ DT.Interval , (-0.4907, 95674.1707) ],
	'atlas_low_employment_2015_update': 	                [ DT.Binary   , (0.0, 1.0) ],
	'atlas_pct_diabetes_adults13': 	                        [ DT.Interval , (2.8, 22.2) ],
	'atlas_pct_laccess_nhasian15': 	                        [ DT.Interval , (-0.5, 10.4636) ],
	'atlas_deep_pov_all': 	                                [ DT.Interval , (0.5672, 38.6865) ],
	'atlas_net_international_migration_rate': 	        [ DT.Interval , (-0.9028, 10.1939) ],
	'atlas_deep_pov_children': 	                        [ DT.Interval , (-0.4998, 55.5641) ],
	'bh_ncdm_pct': 	                                        [ DT.Interval , (-0.5, 12.5) ],
	'auth_3mth_non_er': 	                                [ DT.Interval , (0.0, 1.0, 2.0) ],
	'atlas_foodinsec_child_03_11': 	                        [ DT.Interval , (4.6, 13.3) ],
	'rx_branded_mbr_resp_pmpm_cost': 	                [ DT.Interval , (-0.5, 1649.1575) ],
	'atlas_pc_wic_redemp12': 	                        [ DT.Interval , (-0.3606, 94.0552) ],
	'rwjf_mv_deaths_rate': 	                                [ DT.Interval , (2.4232, 73.9603) ],
	'auth_3mth_acute_cad': 	                                [ DT.Interval , (0, 1) ],
	'atlas_pct_reduced_lunch14': 	                        [ DT.Interval , (-0.5, 21.4477) ],
	'cons_nwperadult': 	                                [ DT.Interval , (-2500.5, 1000000.5) ],
	'total_allowed_pmpm_cost_t_9-6-3m_b4': 	                [ DT.Nominal  , ('Dec_1x-2x', 'Dec_2x-4x', 'Dec_4x-8x', 'Dec_over_8x', 'Inc_1x-2x', 'Inc_2x-4x', 'Inc_4x-8x', 'Inc_over_8x', 'New', 'No Activity', 'No_Change', 'Resolved') ],
	'rx_hum_28_pmpm_cost': 	                                [ DT.Interval , (-0.5, 199.6442) ],
#	'mabh_seg': 	                                        [ DT.Ignore   , ('C1', 'C2', 'C3', 'C4', 'C5', 'C6', 'C7', 'H1', 'H2', 'H3', 'H4', 'H5', 'H6', 'H7', 'H8') ],
	'cms_orig_reas_entitle_cd': 	                        [ DT.Nominal  , (0.0, 1.0, 2.0, 3.0) ],
	'atlas_totalocchu': 	                                [ DT.Interval , (313.5, 3281845.5) ],
	'med_physician_office_ds_clm_6to9m_b4': 	        [ DT.Interval , (119.5, 273.5) ],
	'atlas_pct_loclfarm12': 	                        [ DT.Interval , (-0.5, 80.5) ],
	'rx_generic_mbr_resp_pmpm_cost': 	                [ DT.Interval , (-0.5, 555.8275) ],
	'total_outpatient_mbr_resp_pmpm_cost_6to9m_b4': 	[ DT.Interval , (-0.5, 2780.59) ],
	'rx_gpi4_3400_pmpm_ct': 	                        [ DT.Interval , (-0.5, 4.5) ],
	'lab_dist_loinc_pmpm_ct': 	                        [ DT.Interval , (-0.5, 68.5) ],
	'atlas_pct_nslp15': 	                                [ DT.Interval , (6.1689, 13.3538) ],
	'rx_generic_pmpm_ct_0to3m_b4': 	                        [ DT.Interval , (-0.5, 39.5) ],
	'oontwk_mbr_resp_pmpm_cost_t_6-3-0m_b4': 	        [ DT.Nominal  , ('Dec_1x-2x', 'Dec_2x-4x', 'Dec_4x-8x', 'Dec_over_8x', 'Inc_1x-2x', 'Inc_2x-4x', 'Inc_4x-8x', 'Inc_over_8x', 'New', 'No Activity', 'No_Change', 'Resolved') ],
	'atlas_pct_laccess_lowi15': 	                        [ DT.Interval , (-0.5, 53.1667) ],
	'bh_ncal_ind': 	                                        [ DT.Binary   , (0, 1) ],
	'atlas_pct_fmrkt_sfmnp16': 	                        [ DT.Interval , (-0.5, 100.5) ],
	'hum_region': 	                                        [ DT.Nominal  , ('CALIFORNIA/NEVADA', 'CENTRAL', 'CENTRAL WEST', 'EAST', 'EAST CENTRAL', 'FLORIDA', 'GREAT LAKES/CENTRAL NORTH', 'GULF STATES', 'INTERMOUNTAIN', 'MID-ATLANTIC/NORTH CAROLINA', 'MID-SOUTH', 'NORTHEAST', 'PACIFIC', 'PR', 'SOUTHEAST', 'TEXAS') ],
	'rx_nonmail_dist_gpi6_pmpm_ct_t_9-6-3m_b4': 	        [ DT.Nominal  , ('Dec_1x-2x', 'Dec_2x-4x', 'Dec_4x-8x', 'Dec_over_8x', 'Inc_1x-2x', 'Inc_2x-4x', 'Inc_4x-8x', 'Inc_over_8x', 'New', 'No Activity', 'No_Change', 'Resolved') ],
	'atlas_pct_loclsale12': 	                        [ DT.Interval , (-0.5, 36.3025) ],
	'rej_med_er_net_paid_pmpm_cost_t_9-6-3m_b4': 	        [ DT.Nominal  , ('No Activity', 'No_Change') ],
	'credit_bal_autobank': 	                                [ DT.Interval , (673.7134, 16942.1012) ],
	'med_outpatient_mbr_resp_pmpm_cost_t_9-6-3m_b4':        [ DT.Nominal  , ('Dec_1x-2x', 'Dec_2x-4x', 'Dec_4x-8x', 'Dec_over_8x', 'Inc_1x-2x', 'Inc_2x-4x', 'Inc_4x-8x', 'Inc_over_8x', 'New', 'No Activity', 'No_Change', 'Resolved') ],
	'rx_overall_mbr_resp_pmpm_cost_0to3m_b4': 	        [ DT.Interval , (-0.5, 1754.45) ],
	'rx_tier_2_pmpm_ct_3to6m_b4': 	                        [ DT.Interval , (-0.5, 19.8333) ],
	'rx_nonbh_net_paid_pmpm_cost': 	                        [ DT.Interval , (-0.5, 39533.426) ],
	'rx_maint_pmpm_ct_9to12m_b4': 	                        [ DT.Interval , (-0.5, 36.8333) ],
	'rx_nonbh_net_paid_pmpm_cost_t_6-3-0m_b4':  	        [ DT.Nominal  , ('Dec_1x-2x', 'Dec_2x-4x', 'Dec_4x-8x', 'Dec_over_8x', 'Inc_1x-2x', 'Inc_2x-4x', 'Inc_4x-8x', 'Inc_over_8x', 'New', 'No Activity', 'No_Change', 'Resolved') ],
	'atlas_type_2015_recreation_no': 	                [ DT.Binary   , (0.0, 1.0) ],
	'rx_gpi2_39_pmpm_cost_t_6-3-0m_b4': 	                [ DT.Nominal  , ('Dec_1x-2x', 'Dec_2x-4x', 'Dec_4x-8x', 'Dec_over_8x', 'Inc_1x-2x', 'Inc_2x-4x', 'Inc_4x-8x', 'Inc_over_8x', 'New', 'No Activity', 'No_Change', 'Resolved') ],
	'atlas_type_2015_update': 	                        [ DT.Nominal  , (0.0, 1.0, 2.0, 3.0, 4.0, 5.0) ],
	'cms_risk_adjustment_factor_a_amt': 	                [ DT.Interval , (-0.5, 10.772) ],
	'total_ip_maternity_net_paid_pmpm_cost_t_12-9-6m_b4': 	[ DT.Nominal  , ('No Activity', 'No_Change') ],
	'rx_generic_pmpm_cost': 	                        [ DT.Interval , (-0.5, 3718.7524) ],
	'cmsd2_eye_retina_pmpm_ct': 	                        [ DT.Interval , (-0.5, 2.6667) ],
	'auth_3mth_post_acute': 	                        [ DT.Interval , (0.0, 1.0, 2.0) ],
	'auth_3mth_facility': 	                                [ DT.Interval , (0.0, 1.0, 2.0) ],
	'rx_days_since_last_script_0to3m_b4': 	                [ DT.Interval , (0.5, 120.5) ],
	'atlas_population_loss_2015_update': 	                [ DT.Binary   , (0.0, 1.0) ],
	'rx_maint_pmpm_ct_t_6-3-0m_b4': 	                [ DT.Nominal  , ('Dec_1x-2x', 'Dec_2x-4x', 'Dec_4x-8x', 'Dec_over_8x', 'Inc_1x-2x', 'Inc_2x-4x', 'Inc_4x-8x', 'Inc_over_8x', 'New', 'No Activity', 'No_Change', 'Resolved') ],
	'auth_3mth_acute_mean_los': 	                        [ DT.Interval , (-0.5, 42.5) ],
	'credit_num_autofinance': 	                        [ DT.Interval , (-0.4562, 1.8466) ],
	'cons_rxmaint': 	                                [ DT.Interval , (-0.5, 9.5) ],
	'rx_mail_net_paid_pmpm_cost_t_6-3-0m_b4': 	        [ DT.Nominal  , ('Dec_1x-2x', 'Dec_2x-4x', 'Dec_4x-8x', 'Dec_over_8x', 'Inc_1x-2x', 'Inc_2x-4x', 'Inc_4x-8x', 'Inc_over_8x', 'New', 'No Activity', 'No_Change', 'Resolved') ],
	'auth_3mth_home': 	                                [ DT.Interval , (0.0, 3.0) ],
	'rx_maint_mbr_resp_pmpm_cost_6to9m_b4': 	        [ DT.Interval , (-0.5, 1688.26) ],
	'cons_hxwearbl': 	                                [ DT.Interval , (-0.5, 9.5) ],
	'total_physician_office_mbr_resp_pmpm_cost_t_9-6-3m_b4':[ DT.Nominal  , ('Dec_1x-2x', 'Dec_2x-4x', 'Dec_4x-8x', 'Dec_over_8x', 'Inc_1x-2x', 'Inc_2x-4x', 'Inc_4x-8x', 'Inc_over_8x', 'New', 'No Activity', 'No_Change', 'Resolved') ],
	'atlas_pct_laccess_black15': 	                        [ DT.Interval , (-0.5, 38.0687) ],
	'atlas_hh65plusalonepct': 	                        [ DT.Interval , (2.8088, 24.4709) ],
	'atlas_farm_to_school13': 	                        [ DT.Binary   , (0.0, 1.0) ],
	'auth_3mth_acute_inj': 	                                [ DT.Interval , (0, 1) ],
	'rej_days_since_last_clm': 	                        [ DT.Interval , (2.5, 480.5) ],
	'bh_outpatient_net_paid_pmpm_cost': 	                [ DT.Interval , (-0.5, 1287.05) ],
	'atlas_dirsales_farms12': 	                        [ DT.Interval , (-0.5, 839.5) ],
	'rx_generic_pmpm_cost_6to9m_b4': 	                [ DT.Interval , (-0.5, 4619.73) ],
	'rev_cms_ansth_pmpm_ct': 	                        [ DT.Interval , (-0.5, 1.0) ],
	'atlas_convspth14': 	                                [ DT.Interval , (-0.4999, 3.2462) ],
	'total_med_allowed_pmpm_cost_9to12m_b4': 	        [ DT.Interval , (-0.5, 65189.07) ],
	'rx_mail_mbr_resp_pmpm_cost_t_9-6-3m_b4': 	        [ DT.Nominal  , ('Dec_1x-2x', 'Dec_2x-4x', 'Dec_4x-8x', 'Dec_over_8x', 'Inc_1x-2x', 'Inc_2x-4x', 'Inc_4x-8x', 'Inc_over_8x', 'New', 'No Activity', 'No_Change', 'Resolved') ],
	'med_outpatient_visit_ct_pmpm_t_12-9-6m_b4': 	        [ DT.Nominal  , ('Dec_1x-2x', 'Dec_2x-4x', 'Dec_4x-8x', 'Dec_over_8x', 'Inc_1x-2x', 'Inc_2x-4x', 'Inc_4x-8x', 'Inc_over_8x', 'New', 'No Activity', 'No_Change', 'Resolved') ],
	'rx_nonbh_pmpm_ct_t_9-6-3m_b4': 	                [ DT.Nominal  , ('Dec_1x-2x', 'Dec_2x-4x', 'Dec_4x-8x', 'Dec_over_8x', 'Inc_1x-2x', 'Inc_2x-4x', 'Inc_4x-8x', 'Inc_over_8x', 'New', 'No Activity', 'No_Change', 'Resolved') ],
	'auth_3mth_acute': 	                                [ DT.Interval , (0.0, 4.0) ],
	'rx_nonbh_pmpm_ct_0to3m_b4': 	                        [ DT.Interval , (-0.5, 35.5) ],
	'atlas_pc_ffrsales12': 	                                [ DT.Interval , (363.612, 1035.8916) ],
	'auth_3mth_dc_left_ama': 	                        [ DT.Interval , (0.0, 1.0) ],
	'credit_bal_bankcard_severederog': 	                [ DT.Interval , (-0.4998, 4787.7302) ],
	'atlas_povertyunder18pct': 	                        [ DT.Interval , (2.4, 66.8) ],
	'rx_tier_1_pmpm_ct_0to3m_b4': 	                        [ DT.Interval , (-0.5, 22.1667) ],
	'cons_estinv30_rc': 	                                [ DT.Interval , (2499.5, 1000000.5) ],
	'auth_3mth_bh_acute_men': 	                        [ DT.Interval , (0, 1) ],
	'rx_gpi2_34_pmpm_ct': 	                                [ DT.Interval , (-0.5, 4.5) ],
	'auth_3mth_dc_custodial': 	                        [ DT.Interval , (0.0, 1.0) ],
	'atlas_veg_acrespth12': 	                        [ DT.Interval , (-0.5, 2600.7403) ],
	'atlas_grocpth14': 	                                [ DT.Interval , (-0.5, 2.1155) ],
	'total_med_net_paid_pmpm_cost_t_6-3-0m_b4': 	        [ DT.Nominal  , ('Dec_1x-2x', 'Dec_2x-4x', 'Dec_4x-8x', 'Dec_over_8x', 'Inc_1x-2x', 'Inc_2x-4x', 'Inc_4x-8x', 'Inc_over_8x', 'New', 'No Activity', 'No_Change', 'Resolved') ],
	'rx_gpi2_90_dist_gpi6_pmpm_ct_9to12m_b4': 	        [ DT.Interval , (0, 1.5)],
	'atlas_csa12': 	                                        [ DT.Interval , (-0.5, 88.5) ],
	'sex_cd': 	                                        [ DT.Binary   , ('F', 'M') ],
	'rx_gpi2_62_pmpm_cost_t_9-6-3m_b4': 	                [ DT.Nominal  , ('Dec_1x-2x', 'Dec_2x-4x', 'Dec_4x-8x', 'Dec_over_8x', 'Inc_1x-2x', 'Inc_2x-4x', 'Inc_4x-8x', 'Inc_over_8x', 'New', 'No Activity', 'No_Change', 'Resolved') ],
#	'lang_spoken_cd': 	                                [ DT.Ignore   , ('CHI', 'CRE', 'ENG', 'KOR', 'OTH', 'SPA', 'VIE') ],
	'rx_overall_gpi_pmpm_ct_t_12-9-6m_b4': 	                [ DT.Nominal  , ('Dec_1x-2x', 'Dec_2x-4x', 'Dec_4x-8x', 'Dec_over_8x', 'Inc_1x-2x', 'Inc_2x-4x', 'Inc_4x-8x', 'Inc_over_8x', 'New', 'No Activity', 'No_Change', 'Resolved') ],
	'cons_hhcomp': 	                                        [ DT.Nominal  , ('A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'U') ],
	'auth_3mth_acute_hdz': 	                                [ DT.Interval , (0, 1) ],
	'cons_rxadhs': 	                                        [ DT.Interval , (-0.5, 9.5) ],
	'atlas_pct_fmrkt_snap16': 	                        [ DT.Interval , (-0.5, 100.5) ],
	'met_obe_diag_pct': 	                                [ DT.Interval , (-0.5, 12.5) ],
	'cms_partd_ra_factor_amt': 	                        [ DT.Interval , (-0.5, 12.214) ],
	'atlas_pct_sbp15':                                     	[ DT.Interval , (1.0464, 8.6602) ],
	'rwjf_resident_seg_black_inx': 	                        [ DT.Interval , (-0.2416, 90.8656) ],
	'atlas_pct_cacfp15': 	                                [ DT.Interval , (0.0681, 2.8593) ],
	'auth_3mth_rehab': 	                                [ DT.Interval , (0, 1) ],
	'pdc_lip': 	                                        [ DT.Interval , (-0.3352, 1.6) ],
	'atlas_ffrpth14': 	                                [ DT.Interval , (-0.5, 2.7812) ],
	'credit_num_autobank_new': 	                        [ DT.Interval , (-0.4999, 0.7981) ],
	'rx_tier_2_pmpm_ct': 	                                [ DT.Interval , (-0.5, 18.4167) ],
	'cons_n2pwh': 	                                        [ DT.Interval , (-0.5, 99.5) ],
	'rx_nonmaint_dist_gpi6_pmpm_ct_t_12-9-6m_b4': 	        [ DT.Nominal  , ('Dec_1x-2x', 'Dec_2x-4x', 'Dec_4x-8x', 'Dec_over_8x', 'Inc_1x-2x', 'Inc_2x-4x', 'Inc_4x-8x', 'Inc_over_8x', 'New', 'No Activity', 'No_Change', 'Resolved') ],
#	'atlas_berry_acrespth12': 	                        [ DT.Ignore   , (-0.5, 61.401) ],
	'atlas_pct_fmrkt_credit16': 	                        [ DT.Interval , (-0.5, 100.5) ],
	'atlas_slhouse12': 	                                [ DT.Interval , (-0.5, 23.5) ],
	'atlas_pc_fsrsales12': 	                                [ DT.Interval , (439.2315, 2161.0031) ],
	'credit_hh_1stmtgcredit': 	                        [ DT.Interval , (0.8176, 71.2109) ],
	'auth_3mth_snf_post_hsp': 	                        [ DT.Interval , (0.0, 2.0) ],
	'atlas_pct_fmrkt_wiccash16': 	                        [ DT.Interval , (-0.5, 100.5) ],
	'atlas_foodinsec_13_15': 	                        [ DT.Interval , (8.0, 21.3) ],
	'cons_rxadhm': 	                                        [ DT.Interval , (-0.5, 9.5) ],
	'atlas_fmrktpth16': 	                                [ DT.Interval , (-0.5, 1.2396) ],
	'rx_nonotc_pmpm_cost_t_6-3-0m_b4': 	                [ DT.Nominal  , ('Dec_1x-2x', 'Dec_2x-4x', 'Dec_4x-8x', 'Dec_over_8x', 'Inc_1x-2x', 'Inc_2x-4x', 'Inc_4x-8x', 'Inc_over_8x', 'New', 'No Activity', 'No_Change', 'Resolved') ],
	'cci_dia_m_pmpm_ct': 	                                [ DT.Interval , (-0.5, 15.8333) ],
	'cons_n2phi': 	                                        [ DT.Interval , (-0.5, 99.5) ],
	'bh_physician_office_copay_pmpm_cost_6to9m_b4': 	[ DT.Interval , (-0.5, 57.78) ],
	'rwjf_income_inequ_ratio': 	                        [ DT.Interval , (2.47, 9.429) ],
	'rej_total_physician_office_visit_ct_pmpm_0to3m_b4': 	[ DT.Interval , (0.0, 2.0) ],
	'credit_num_nonmtgcredit_60dpd': 	                [ DT.Interval , (-0.475, 2.6726) ],
	'credit_bal_autofinance_new': 	                        [ DT.Interval , (3.004, 7448.1231) ],
	'rwjf_men_hlth_prov_ratio': 	                        [ DT.Interval , (-0.5, 0.51) ],
	'auth_3mth_dc_home_health': 	                        [ DT.Interval , (0.0, 2.0) ],
	'rx_gpi2_56_dist_gpi6_pmpm_ct_3to6m_b4': 	        [ DT.Interval , (0.0, 1.0) ],
	'cmsd2_sns_genitourinary_pmpm_ct': 	                [ DT.Interval , (-0.5, 6.3333) ],
	'auth_3mth_acute_cir': 	                                [ DT.Interval , (0, 1) ],
	'med_ambulance_coins_pmpm_cost_t_9-6-3m_b4': 	        [ DT.Nominal  , ('Inc_1x-2x', 'New', 'No Activity', 'No_Change', 'Resolved') ],
#	'hedis_dia_hba1c_ge9': 	                                [ DT.Ignore   , ('N', 'Y') ],
	'bh_ncal_pct': 	                                        [ DT.Interval , (-0.5, 12.5) ],
	'atlas_pct_snap16': 	                                [ DT.Interval , (5.3178, 23.2637) ],
	'ccsp_227_pct': 	                                [ DT.Interval , (-0.5, 12.5) ],
#	'atlas_ghveg_sqftpth12': 	                        [ DT.Ignore   , (-0.5, 11244.3574) ],
	'rx_days_since_last_script_6to9m_b4': 	                [ DT.Interval , (-0.5, 274.5) ],
	'atlas_orchard_acrespth12': 	                        [ DT.Interval , (-0.5, 900.5) ],
	'atlas_persistentchildpoverty_1980_2011': 	        [ DT.Binary   , (0.0, 1.0) ],
	'atlas_pct_laccess_multir15': 	                        [ DT.Interval , (-0.5, 16.553) ],
	'cons_cgqs': 	                                        [ DT.Interval , (59.5, 170.5) ],
	'ccsp_065_pmpm_ct': 	                                [ DT.Interval , (0.0, 0.18) ],
	'atlas_medhhinc': 	                                [ DT.Interval , (22044.5, 134609.5) ],
	'rx_maint_net_paid_pmpm_cost_t_9-6-3m_b4': 	        [ DT.Nominal  , ('Dec_1x-2x', 'Dec_2x-4x', 'Dec_4x-8x', 'Dec_over_8x', 'Inc_1x-2x', 'Inc_2x-4x', 'Inc_4x-8x', 'Inc_over_8x', 'New', 'No Activity', 'No_Change', 'Resolved') ],
	'rwjf_mental_distress_pct': 	                        [ DT.Interval , (-0.4197, 0.6937) ],
	'bh_ip_snf_admit_days_pmpm_t_9-6-3m_b4': 	        [ DT.Nominal  , ('No Activity', 'No_Change') ],
	'rx_phar_cat_cvs_pmpm_ct_t_9-6-3m_b4': 	                [ DT.Nominal  , ('Dec_1x-2x', 'Dec_2x-4x', 'Dec_4x-8x', 'Dec_over_8x', 'Inc_1x-2x', 'Inc_2x-4x', 'Inc_4x-8x', 'Inc_over_8x', 'New', 'No Activity', 'No_Change', 'Resolved') ],
	'zip_cd': 	                                        [ DT.Interval , (601.5, 99827.5) ],
	'atlas_pct_laccess_nhpi15': 	                        [ DT.Interval , (-0.5, 4.7699) ],
	'auth_3mth_post_er': 	                                [ DT.Interval , (0.0, 3.0) ],
	'credit_num_consumerfinance_new': 	                [ DT.Interval , (-0.4805, 1.4977) ],
	'rx_gpi2_49_pmpm_cost_0to3m_b4': 	                [ DT.Interval , (-0.5, 651.5933) ],
	'cons_chva': 	                                        [ DT.Interval , (-0.5, 999.5) ],
	'atlas_avghhsize': 	                                [ DT.Interval , (1.25, 4.38) ],
	'rx_overall_net_paid_pmpm_cost_6to9m_b4': 	        [ DT.Interval , (-0.5, 41736.332) ],
	'atlas_ownhomepct': 	                                [ DT.Interval , (18.5669, 92.8509) ],
	'atlas_orchard_farms12': 	                        [ DT.Interval , (-0.5, 4124.5) ],
	'total_physician_office_visit_ct_pmpm_t_6-3-0m_b4': 	[ DT.Nominal  , ('Dec_1x-2x', 'Dec_2x-4x', 'Dec_4x-8x', 'Inc_1x-2x', 'Inc_2x-4x', 'Inc_4x-8x', 'Inc_over_8x', 'New', 'No Activity', 'No_Change', 'Resolved') ],
	'atlas_pct_fmrkt_wic16': 	                        [ DT.Interval , (-0.5, 100.5) ],
	'rx_gpi2_33_pmpm_ct_0to3m_b4': 	                        [ DT.Interval , (0.0, 2.5) ],
	'rwjf_social_associate_rate': 	                        [ DT.Interval , (-0.4953, 49.1772) ],
	'atlas_freshveg_farms12': 	                        [ DT.Interval , (-0.5, 802.5) ],
	'auth_3mth_acute_sns': 	                                [ DT.Interval , (0, 1) ],
	'days_since_last_clm_0to3m_b4': 	                [ DT.Interval , (2.5, 120.5) ],
	'auth_3mth_dc_other': 	                                [ DT.Interval , (0.0, 1.0) ],
	'auth_3mth_bh_acute_mean_los': 	                        [ DT.Interval , (0.0, 5.0) ],
	'mcc_end_pct': 	                                        [ DT.Interval , (-0.5, 12.5) ],
	'cons_lwcm07': 	                                        [ DT.Interval , (-0.4628, 1.2202) ],
	'atlas_pct_fmrkt_otherfood16': 	                        [ DT.Interval , (-0.5, 100.5) ],
	'auth_3mth_acute_mus': 	                                [ DT.Interval , (0.0, 1.0) ],
	'atlas_perpov_1980_0711': 	                        [ DT.Binary   , (0.0, 1.0) ],
	'atlas_pct_laccess_white15': 	                        [ DT.Interval , (-0.5, 92.5787) ],
	'auth_3mth_post_acute_mean_los': 	                [ DT.Interval , (-0.5, 43.5) ],
	'rx_gpi2_66_pmpm_ct': 	                                [ DT.Interval , (-0.5, 3.2273) ],
	'auth_3mth_acute_gus':                                  [ DT.Interval , (0, 1) ],
	'rx_generic_dist_gpi6_pmpm_ct_t_9-6-3m_b4': 	        [ DT.Nominal  , ('Dec_1x-2x', 'Dec_2x-4x', 'Dec_4x-8x', 'Dec_over_8x', 'Inc_1x-2x', 'Inc_2x-4x', 'Inc_4x-8x', 'Inc_over_8x', 'New', 'No Activity', 'No_Change', 'Resolved') ],
	'atlas_low_education_2015_update': 	                [ DT.Binary   , (0.0, 1.0) ],
	'race_cd': 	                                        [ DT.Nominal  , (0.0, 1.0, 2.0, 3.0, 4.0, 5.0, 6.0) ]}


target='covid_vaccination'

rie = ReplaceImputeEncode(data_map = data_map,binary_encoding='one-hot',
                          nominal_encoding='one-hot',no_impute=[target],
                          drop=True,display=True)

encoded_df = rie.fit_transform(training_clean_full)
